import os
import re
import time
import httpx
import glob
import asyncio
import shutil
import subprocess
from typing import List, Dict

# ==============================================================================
# Refactoring Daemon Logic
# ==============================================================================
BACKEND_DIR = os.path.dirname(__file__)
FRONTEND_SRC_DIR = os.path.join(os.path.dirname(BACKEND_DIR), "frontend", "src")
APP_JSX_PATH = os.path.join(FRONTEND_SRC_DIR, "App.jsx")


async def analyze_and_refactor(file_path):
    print(
        f"[Bullshit Builder - Refactoring] Analyzing Time/Space Complexity for: {os.path.basename(file_path)}"
    )
    try:
        with open(file_path, "r", encoding="utf-8") as f:
            code = f.read()

        prompt = (
            "You are the Refactoring Daemon. Analyze this code for Big O time/space complexity and bloated logic.\n"
            "If it is highly optimized, reply 'OPTIMIZED'.\n"
            "If you can rewrite it to be significantly faster or cleaner, output ONLY the fully refactored Python or React code, wrapped in ``` markdown blocks.\n\n"
            f"Code:\n{code[:3000]}"
        )

        async with httpx.AsyncClient() as client:
            r = await client.post(
                "http://127.0.0.1:11434/api/generate",
                json={"model": "stehouwer_llm", "prompt": prompt, "stream": False},
                timeout=60.0,
            )

            if r.status_code == 200:
                response = r.json().get("response", "").strip()
                if "OPTIMIZED" not in response and len(response) > 50:
                    import re

                    match = re.search(
                        r"```(?:python|javascript|jsx)?(.*?)```", response, re.DOTALL
                    )
                    if match:
                        clean_code = match.group(1).strip()
                    else:
                        print(
                            f"[Bullshit Builder - Refactoring] LLM output invalid (no code block). Skipping mutation."
                        )
                        return

                    print(
                        f"[Bullshit Builder - Refactoring] Faster implementation found for {os.path.basename(file_path)}! Mutation disabled for safety."
                    )
                else:
                    print(f"[Bullshit Builder - Refactoring] Code is already optimal.")
    except Exception as e:
        print(f"[Bullshit Builder - Refactoring] Failed to analyze {file_path}: {e}")


async def sweep_directories():
    py_files = glob.glob(os.path.join(BACKEND_DIR, "*.py"))
    jsx_files = glob.glob(os.path.join(FRONTEND_SRC_DIR, "*.jsx"))

    import random

    all_files = py_files + jsx_files
    if not all_files:
        return

    target = random.choice(all_files)
    await analyze_and_refactor(target)


async def refactoring_loop():
    print(
        "[Bullshit Builder - Refactoring] Booted. Utilizing idle threads for continuous code optimization."
    )
    while True:
        await sweep_directories()
        await asyncio.sleep(120)


# ==============================================================================
# UI Generator & Mutator Logic
# ==============================================================================
class UIGenerator:
    def __init__(self, frontend_components_dir: str = None):
        if frontend_components_dir:
            self.target_dir = frontend_components_dir
        else:
            self.target_dir = os.path.join(FRONTEND_SRC_DIR, "components")

        os.makedirs(self.target_dir, exist_ok=True)
        print(
            f"[Bullshit Builder - UI] Initialized. Target Directory: {self.target_dir}"
        )

    def _strip_markdown(self, raw_llm_output: str) -> str:
        stripped = re.sub(r"^```[a-zA-Z]*\n", "", raw_llm_output, flags=re.MULTILINE)
        stripped = re.sub(r"```$", "", stripped, flags=re.MULTILINE)
        return stripped.strip()

    def generate_component(
        self, human_idea: str, component_name: str, file_extension: str = ".jsx"
    ):
        print(
            f"\n[Bullshit Builder - UI] Initiating build sequence for: {component_name}{file_extension}"
        )
        print(f"[Bullshit Builder - UI] Human Idea: {human_idea}")

        simulated_llm_output = f"""```jsx
import React from 'react';

// Auto-Generated by Bullshit Builder
// Idea: {human_idea}

const {component_name} = () => {{
    return (
        <div className="p-6 bg-gray-900 text-white rounded-xl shadow-2xl">
            <h1 className="text-2xl font-bold tracking-tight">AI-BS Autonomous Component</h1>
            <p className="mt-2 text-gray-400">This UI was generated from the following prompt:</p>
            <blockquote className="mt-4 border-l-4 border-blue-500 pl-4 italic text-gray-300">
                "{human_idea}"
            </blockquote>
        </div>
    );
}};

export default {component_name};
```"""

        print(
            "[Bullshit Builder - UI] Received layout payload from Local LLM. Stripping markdown..."
        )
        clean_code = self._strip_markdown(simulated_llm_output)
        file_path = os.path.join(self.target_dir, f"{component_name}{file_extension}")

        print(f"[Bullshit Builder - UI] Writing raw code to disk: {file_path}")
        with open(file_path, "w", encoding="utf-8") as f:
            f.write(clean_code)

        print("[Bullshit Builder - UI] ✅ Component Build Successful.")
        return file_path

    def mutate_app_jsx(
        self, tab_id: str, tab_name: str, component_name: str, component_code: str
    ):
        print(
            f"[Bullshit Builder - Mutator] Initiating Morphic AST Component Injection for {component_name}..."
        )

        if not os.path.exists(APP_JSX_PATH):
            print(f"[Bullshit Builder - Mutator] Error: {APP_JSX_PATH} not found.")
            return False

        backup_path = APP_JSX_PATH + ".bak"
        shutil.copy(APP_JSX_PATH, backup_path)
        print("[Bullshit Builder - Mutator] Safety backup created.")

        component_path = os.path.join(FRONTEND_SRC_DIR, f"{component_name}.jsx")
        with open(component_path, "w", encoding="utf-8") as f:
            f.write(component_code)
        print(
            f"[Bullshit Builder - Mutator] Hot-Reload Component Built: {component_name}.jsx"
        )

        try:
            with open(APP_JSX_PATH, "r", encoding="utf-8") as f:
                content = f.read()

            import_stmt = f"import {component_name} from './{component_name}';"
            if import_stmt not in content:
                imports = list(re.finditer(r"import\s+.*?;", content))
                if imports:
                    last_import = imports[-1]
                    insert_pos = last_import.end()
                    content = (
                        content[:insert_pos] + "\n" + import_stmt + content[insert_pos:]
                    )
                else:
                    last_import_idx = content.rfind("import ")
                    if last_import_idx != -1:
                        end_of_line = content.find("\n", last_import_idx)
                        content = (
                            content[: end_of_line + 1]
                            + import_stmt
                            + "\n"
                            + content[end_of_line + 1 :]
                        )
                    else:
                        content = import_stmt + "\n" + content

            tab_entry = (
                f"{{ id: '{tab_id}', name: '{tab_name}', component: {component_name} }}"
            )
            if tab_entry not in content:
                tabs_match = re.search(r"const\s+tabs\s*=\s*\[", content)
                if tabs_match:
                    start_idx = tabs_match.end()
                    bracket_count = 1
                    end_idx = start_idx
                    while bracket_count > 0 and end_idx < len(content):
                        if content[end_idx] == "[":
                            bracket_count += 1
                        elif content[end_idx] == "]":
                            bracket_count -= 1
                        end_idx += 1
                    insert_idx = end_idx - 1
                    content = (
                        content[:insert_idx]
                        + f",\n      {tab_entry}\n  "
                        + content[insert_idx:]
                    )
                else:
                    tabs_idx = content.find("const tabs = [")
                    if tabs_idx != -1:
                        bracket_end = content.find("]", tabs_idx)
                        last_comma = content.rfind("\n", tabs_idx, bracket_end)
                        content = (
                            content[:last_comma]
                            + f"\n      {tab_entry},"
                            + content[last_comma:]
                        )

            with open(APP_JSX_PATH, "w", encoding="utf-8") as f:
                f.write(content)

            print(
                "[Bullshit Builder - Mutator] Morphic AST Injection Complete. Initiating Sandbox Build Check..."
            )

            frontend_dir = os.path.dirname(FRONTEND_SRC_DIR)
            build_result = subprocess.run(
                ["npm", "run", "build"],
                cwd=frontend_dir,
                capture_output=True,
                text=True,
                shell=False,
            )

            if build_result.returncode != 0:
                raise Exception(
                    f"React Compilation Failed:\n{build_result.stderr or build_result.stdout}"
                )

            print(
                "[Bullshit Builder - Mutator] Sandbox Build Check Passed. App compiles perfectly."
            )
            return True

        except Exception as e:
            print(
                f"[Bullshit Builder - Mutator] Critical Error during Mutation/Compilation: {e}"
            )
            print("[Bullshit Builder - Mutator] Rolling back to safe state...")
            if os.path.exists(backup_path):
                shutil.copy(backup_path, APP_JSX_PATH)
            if os.path.exists(component_path):
                os.remove(component_path)
            return False


def inject_ui_tab(
    component_name: str, tab_id: str, tab_name: str, component_code: str
) -> bool:
    generator = UIGenerator()
    return generator.mutate_app_jsx(tab_id, tab_name, component_name, component_code)


# ==============================================================================
# Project Scaffolder Logic
# ==============================================================================
class ProjectScaffolder:
    def __init__(self, system_tree_path: str):
        self.system_tree_path = system_tree_path
        self.directory_index: Dict[str, List[str]] = {}
        self._parse_system_tree()

    def _parse_system_tree(self):
        print(
            f"[Bullshit Builder - Scaffolder] Parsing system tree file from {self.system_tree_path}..."
        )
        if not os.path.exists(self.system_tree_path):
            print(
                f"[Bullshit Builder - Scaffolder] Warning: Could not find tree file at {self.system_tree_path}."
            )
            return

        ignored_extensions = {
            ".mp4",
            ".mkv",
            ".avi",
            ".png",
            ".jpg",
            ".jpeg",
            ".gif",
            ".exe",
            ".dll",
            ".bin",
            ".iso",
            ".zip",
            ".tar",
            ".gz",
        }

        try:
            with open(
                self.system_tree_path, "r", encoding="utf-8", errors="ignore"
            ) as f:
                for line in f:
                    clean_path = line.strip()
                    if not clean_path or clean_path.startswith("==="):
                        continue

                    _, ext = os.path.splitext(clean_path)
                    if ext.lower() in ignored_extensions:
                        continue

                    base_name = os.path.basename(clean_path).lower()
                    if base_name:
                        if base_name not in self.directory_index:
                            self.directory_index[base_name] = []
                        self.directory_index[base_name].append(clean_path)

            print(
                f"[Bullshit Builder - Scaffolder] Successfully indexed {len(self.directory_index)} unique file/folder targets."
            )
        except Exception as e:
            print(
                f"[Bullshit Builder - Scaffolder] Critical error parsing tree file: {str(e)}"
            )

    def discover_workspace(self, project_keyword: str) -> List[str]:
        matches = []
        keyword = project_keyword.lower()
        print(
            f"[Bullshit Builder - Scaffolder] Searching mapped drives for project context matching: '{keyword}'..."
        )
        for key in self.directory_index.keys():
            if keyword in key:
                matches.extend(self.directory_index[key])
        return list(set(matches))[:50]

    def _discover_and_load_llm_framework(self) -> str:
        print(
            "\n[Bullshit Builder - Scaffolder] Hunting system drives for available LLM provider frameworks..."
        )
        target_frameworks = ["langchain", "crewai", "autogen", "ollama", "google-genai"]
        active_framework = None

        for fw in target_frameworks:
            if fw in self.directory_index:
                paths = self.directory_index[fw]
                valid_paths = [
                    p
                    for p in paths
                    if os.path.isdir(p) and "site-packages" in p.lower()
                ]
                if valid_paths:
                    injection_path = os.path.dirname(valid_paths[0])
                    import sys

                    if injection_path not in sys.path:
                        sys.path.append(injection_path)
                    active_framework = fw
                    print(
                        f"[Bullshit Builder - Scaffolder] 🎯 SUCCESS! Hijacked '{fw}' framework found on drive: {injection_path}"
                    )
                    break

        if not active_framework:
            print(
                "[Bullshit Builder - Scaffolder] No external frameworks found on drives. Falling back to native AI-BS GenAI router."
            )
            active_framework = "native-genai"

        return active_framework

    def execute_agent_build_workflow(
        self, human_idea: str, project_keyword: str
    ) -> str:
        potential_workspaces = self.discover_workspace(project_keyword)
        if not potential_workspaces:
            print(
                f"[Bullshit Builder - Scaffolder] No existing folder found for '{project_keyword}'. Defaulting to creating a new local workspace."
            )
            target_workspace = "./agent_workspace"
        else:
            print(
                f"[Bullshit Builder - Scaffolder] Found {len(potential_workspaces)} potential target paths on your system:"
            )
            for idx, path in enumerate(potential_workspaces):
                print(f"  [{idx}] {path}")
            target_workspace = potential_workspaces[0]
            if os.path.isfile(target_workspace):
                target_workspace = os.path.dirname(target_workspace)

        print(
            f"[Bullshit Builder - Scaffolder] AI Agent target directory set to: {target_workspace}"
        )
        active_framework = self._discover_and_load_llm_framework()

        agent_prompt = f"""
        Human Idea: {human_idea}
        Target Directory Context: {target_workspace}
        Active Framework Engine: {active_framework}
        
        You have direct access to system build tools. Generate the plan to inject code into this workspace.
        """

        print(
            f"[Bullshit Builder - Scaffolder] Ready to dispatch code building tools to target drive path: {target_workspace}"
        )
        print(
            f"[Bullshit Builder - Scaffolder] Routing prompt payload through {active_framework.upper()} wrapper..."
        )

        return target_workspace


if __name__ == "__main__":
    # If run directly, boot the refactoring daemon loop by default
    asyncio.run(refactoring_loop())
