// AUTO-GENERATED BY scripts/generate_schemas.py - DO NOT EDIT MANUALLY
package types

type AudioEventSchema struct {
	TrackId string `json:"track_id"`
	Note string `json:"note"`
	Step int `json:"step"`
	Duration float64 `json:"duration"`
	Velocity float64 `json:"velocity"`
	Bpm int `json:"bpm"`
	PatternId int `json:"pattern_id"`
}

type LeadSchema struct {
	Id string `json:"id"`
	ClientName string `json:"client_name"`
	PropertyType string `json:"property_type"`
	SqFt float64 `json:"sq_ft"`
	EstimatedValue float64 `json:"estimated_value"`
	Status string `json:"status"`
	Timestamp float64 `json:"timestamp"`
}

type TelemetrySchema struct {
	CpuUsage float64 `json:"cpu_usage"`
	GpuUsage float64 `json:"gpu_usage"`
	VramFreeGb float64 `json:"vram_free_gb"`
	VramTotalGb float64 `json:"vram_total_gb"`
	ShmPacketsPerSec float64 `json:"shm_packets_per_sec"`
	Status string `json:"status"`
	Timestamp float64 `json:"timestamp"`
}

type VRAMBudgetSchema struct {
	Requester string `json:"requester"`
	RequiredVramGb float64 `json:"required_vram_gb"`
	AutoEvict bool `json:"auto_evict"`
	Granted bool `json:"granted"`
	FreeVramGb float64 `json:"free_vram_gb"`
	Timestamp float64 `json:"timestamp"`
}

