// AUTO-GENERATED BY scripts/generate_schemas.py - DO NOT EDIT MANUALLY
use serde::{Serialize, Deserialize};

#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct AudioEventSchema {
    pub track_id: String,
    pub note: String,
    pub step: i64,
    pub duration: Option<f64>,
    pub velocity: Option<f64>,
    pub bpm: Option<i64>,
    pub pattern_id: Option<i64>,
}

#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct LeadSchema {
    pub id: Option<String>,
    pub client_name: String,
    pub property_type: Option<String>,
    pub sq_ft: f64,
    pub estimated_value: f64,
    pub status: Option<String>,
    pub timestamp: Option<f64>,
}

#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct TelemetrySchema {
    pub cpu_usage: f64,
    pub gpu_usage: Option<f64>,
    pub vram_free_gb: f64,
    pub vram_total_gb: f64,
    pub shm_packets_per_sec: Option<f64>,
    pub status: Option<String>,
    pub timestamp: Option<f64>,
}

#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct VRAMBudgetSchema {
    pub requester: String,
    pub required_vram_gb: f64,
    pub auto_evict: Option<bool>,
    pub granted: Option<bool>,
    pub free_vram_gb: Option<f64>,
    pub timestamp: Option<f64>,
}

